### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by ChinaVolvocars** [adrianwitaszak/PexWallpapers#1]
E:\Github\PexWallpapers\data\build\tmp\kapt3\stubs\debug\com\adwi\data\database\dao\DailyDao.java:17: 警告: The query returns some columns [wallpaperId] which are not used by com.adwi.data.database.domain.WallpaperEntity. You can use @ColumnInfo annotation on the fields to specify the mapping. You can annotate the method with @RewriteQueriesToDropUnusedColumns to direct Room to rewrite your query to avoid fetching unused columns.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: wallpaperId, id, height, url, photographer, imageUrl, categoryName, isFavorite, imageUrlPortrait, imageUrlLandscape, imageUrlTiny, updatedAt. Fields in com.adwi.data.database.domain.WallpaperEntity: id, height, url, photographer, imageUrl, categoryName, isFavorite, imageUrlPortrait, imageUrlLandscape, imageUrlTiny, updatedAt.
    public abstract kotlinx.coroutines.flow.Flow<java.util.List<com.adwi.data.database.domain.WallpaperEntity>> getAllDailyWallpapers();
                                                                                                                ^

E:\Github\PexWallpapers\data\build\tmp\kapt3\stubs\debug\com\adwi\data\database\dao\WallpapersDao.java:61: 警告: The query returns some columns [wallpaperId] which are not used by com.adwi.data.database.domain.WallpaperEntity. You can use @ColumnInfo annotation on the fields to specify the mapping. You can annotate the method with @RewriteQueriesToDropUnusedColumns to direct Room to rewrite your query to avoid fetching unused columns.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: wallpaperId, id, height, url, photographer, imageUrl, categoryName, isFavorite, imageUrlPortrait, imageUrlLandscape, imageUrlTiny, updatedAt. Fields in com.adwi.data.database.domain.WallpaperEntity: id, height, url, photographer, imageUrl, categoryName, isFavorite, imageUrlPortrait, imageUrlLandscape, imageUrlTiny, updatedAt.
    public abstract kotlinx.coroutines.flow.Flow<java.util.List<com.adwi.data.database.domain.WallpaperEntity>> getAllCuratedWallpapers();
                         

                 E:\Github\PexWallpapers\data\build\tmp\kapt3\stubs\debug\com\adwi\data\database\dao\SearchDao.java:17: 警告: The query returns some columns [searchQuery, wallpaperId, queryPosition] which are not used by com.adwi.data.database.domain.WallpaperEntity. You can use @ColumnInfo annotation on the fields to specify the mapping. You can annotate the method with @RewriteQueriesToDropUnusedColumns to direct Room to rewrite your query to avoid fetching unused columns.  You can suppress this warning by annotating the method with @SuppressWarnings(RoomWarnings.CURSOR_MISMATCH). Columns returned by the query: searchQuery, wallpaperId, queryPosition, id, height, url, photographer, imageUrl, categoryName, isFavorite, imageUrlPortrait, imageUrlLandscape, imageUrlTiny, updatedAt. Fields in com.adwi.data.database.domain.WallpaperEntity: id, height, url, photographer, imageUrl, categoryName, isFavorite, imageUrlPortrait, imageUrlLandscape, imageUrlTiny, updatedAt.
    public abstract androidx.paging.PagingSource<java.lang.Integer, com.adwi.data.database.domain.WallpaperEntity> getSearchResultWallpaperPaged(@org.jetbrains.annotations.NotNull()
                                                                                                                   ^                                                                      ^

**Comment by adrianwitaszak** [comment]
Please check current build. Issue sorted
