### ISSUE TITLE
Hilt issue / Build Exception

### ISSUE THREAD

**Issue by ishdemon** [adrianwitaszak/PexWallpapers#3]
> Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':data'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:75)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:68)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:51)

The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.` In Data module.
Apparently its reported before ..tried to fix it but so far no luck.
https://github.com/google/dagger/issues/2661

**Comment by ali-digitify** [comment]
Any luck?

**Comment by ishdemon** [comment]
none.. Tried diff versions.. Applied     
```
const val hiltCoreBase = "com.google.dagger:dagger:${Versions.hilt}"
const val hiltCoreCompiler = "com.google.dagger:dagger-compiler:${Versions.hilt}"
```
Still no luck. This project uses Plugin DSL..no idea if thats the issue..

**Comment by ishdemon** [comment]
@ali-digitify comment this line `id(Plugins.DAGGER_HILT)` in data module's _build.gradle_ once & sync once. It should build successful. then Uncomment it & sync again.

Also dont forget to have `pex_api_access_key="2xxxxxxxxxxxxxxxxxxxxxxx"`
